# Generated by Django 5.0.4 on 2024-05-01 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizedProcessor',
            fields=[
                ('processor_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('processor_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('creater_id', models.BigIntegerField()),
                ('script_text', models.TextField(db_comment='The script of a step.')),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('workflow_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('workflow_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('creater_id', models.BigIntegerField()),
                ('create_date', models.DateTimeField(db_comment='date created')),
                ('update_date', models.DateTimeField(db_comment='date of last update')),
                ('workflow_json', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ResultVariables',
            fields=[
                ('variables_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('executer_id', models.BigIntegerField()),
                ('create_date', models.DateTimeField(db_comment='date created')),
                ('update_date', models.DateTimeField(db_comment='date of last update')),
                ('seriallized_variables', models.TextField(db_comment='The variables preserved.')),
                ('workflow_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowchartagent.workflow')),
            ],
        ),
    ]
