# Generated by Django 5.0.4 on 2024-05-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowchartagent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customizedprocessor',
            name='script_text',
        ),
        migrations.AddField(
            model_name='customizedprocessor',
            name='step_json',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
