# Generated by Django 5.0.4 on 2024-05-19 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowchartagent', '0002_remove_customizedprocessor_script_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizedprocessor',
            name='processor_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resultvariables',
            name='variables_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='workflow_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
